version: '3.7'

services:
  # CPUで実行する用
  sandbox_cpu:
    build:
      context: .
      dockerfile: Dockerfile_cpu
    volumes:
        - .:/home/

  # GPUで実行する用
  sandbox_gpu:
    build:
      context: .
      dockerfile: Dockerfile_gpu
    volumes:
        - .:/home/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [utility, compute, video]
  
